### ISSUE TITLE
build is ignored?

### ISSUE THREAD

**Issue by bishop-exe** [huytd/lichess-tv#1]
.gitignore has _./build_ ignored so no make file.

**Comment by huytd** [comment]
Hey, thanks for the feedback. I put the information in the README.md file

You can do:

```
$ ./setup.sh
$ ./build.sh
```

The setup script will create the build folder, and the build script will run make, as well as run the binary afterward (if build successes).

**Comment by bishop-exe** [comment]
Awesome thank you. I needed to do a few extra things as well but it runs fine due to missing packages. Namely: 
`sudo apt-get install  libcurl4-openssl-dev` 

Minus this "M-" issue...

![image](https://user-images.githubusercontent.com/43148837/191874644-fcc4d88b-ff7b-4588-b98c-fba4ab1cd810.png)

I looked around for an answer and came across this:

https://yjlv.blogspot.com/2015/10/displaying-unicode-with-ncurses-in-c.html#cfd5-addstr-to-addwstr

**Comment by huytd** [comment]
That's interesting, look like it's because I dev on a mac machine and `ncurses` on mac already supported wide characters, for the case of Linux system, we have to link against `ncursesw`.

I'll try setup a linux box and fix up the build next week. Thank you so much!

**Comment by huytd** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/613943/195283930-2870d6c8-acbe-4fc9-b8ae-eb7fed37b7b3.png">

It should be displayed properly on Linux now.

**Comment by bishop-exe** [comment]
Well done!
